version: '3.9'
networks:
  apl-network:

services:
  application: 
    container_name: 'application'
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3344:3344
    networks:
      - apl-network
    volumes:
      - ./:/usr/src/


  pg:
    container_name: db-apl
    image: postgres:13-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=apl
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5441:5432
    networks:
      - apl-network

volumes:
  pg-data:
